org.gradle.jvmargs=-Xmx12g -Xms256m -XX:MaxMetaspaceSize=1g -XX:+UseParallelGC
android.useAndroidX=true
android.experimental.androidTest.numManagedDeviceShards=4
org.gradle.configuration-cache=true
# We never want to use auto-provisioning, as it breaks reproducible builds.
# This should not be a problem, because we never configure a "javaRepositories"
# item to tell Gradle where to auto-provision the toolchain from, but adding
# this flag adds an extra layer of protection.
# See: https://docs.gradle.org/current/userguide/toolchains.html#sub:disable_auto_provision
org.gradle.java.installations.auto-download=false

# Uncomment these to build libsignal from source.
# libsignalClientPath=../libsignal
# org.gradle.dependency.verification=lenient

# 开启并行编译
org.gradle.parallel=true
# 开启守护进程
org.gradle.daemon=true

#启用 Kotlin 增量编译
kotlin.incremental=true
#并行编译 Kotlin 代码
kotlin.parallel.tasks.increase=true

android.enableJetifier=false

org.gradle.cache.remote.allowInsecure=true
org.gradle.caching.remote.debug=true
org.gradle.caching.debug=true
